# Generated by Django 5.2.3 on 2026-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason provided when order was cancelled', null=True),
        ),
    ]
