# Generated by Django 5.2.3 on 2026-02-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashshift_shift_number'),
        ('pos', '0003_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='finance.cashshift'),
        ),
    ]
