# Generated by Django 5.2.11 on 2026-02-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_menucategory_show_in_pos'),
        ('pos', '0004_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, help_text='Specific flavor/size if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariation'),
        ),
    ]
