# Generated by Django 5.2.11 on 2026-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='waitless', max_length=255)),
                ('brand_phone', models.CharField(default='01099641402', max_length=20)),
                ('logo_base64', models.TextField(blank=True, help_text='Base64 encoded string for branding', null=True)),
                ('social_link', models.URLField(blank=True, help_text='Single URL for QR generation (e.g. Linktree)', null=True)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=14.0, help_text='VAT as a percentage (e.g., 14.00)', max_digits=5)),
                ('service_percentage', models.DecimalField(decimal_places=2, default=12.0, help_text='Service charge as a percentage', max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False, help_text='Is VAT included in menu prices?')),
                ('enable_tips', models.BooleanField(default=True, help_text='Prompt for tips on POS?')),
                ('address', models.TextField(blank=True, help_text='Physical branch address for receipts', null=True)),
                ('wifi_password', models.CharField(blank=True, help_text='Optional Wi-Fi password for receipts', max_length=50, null=True)),
                ('receipt_ending_message', models.TextField(default='Thank you for visiting waitless!', help_text='Message at the bottom of the printed receipt')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
