# Generated by Django 5.2.3 on 2026-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='receipt_ending_message',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='service_percentage',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='vat_percentage',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='operating_hours',
            field=models.TextField(blank=True, help_text='JSON or text string representing operating hours', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_footer_msg',
            field=models.TextField(default='Thank you for visiting waitless!', help_text='Message at the bottom of the printed receipt'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_header_msg',
            field=models.TextField(blank=True, help_text='Message at the top of the printed receipt', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_printer_type',
            field=models.CharField(choices=[('thermal80', 'Thermal 80mm'), ('thermal72', 'Thermal 72mm'), ('a4', 'Standard A4'), ('a5', 'Standard A5')], default='thermal80', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='service_charge_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Service charge as a percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tax_label',
            field=models.CharField(default='VAT', help_text='Label for taxes on receipts', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Tax as a percentage (e.g., 14.00)', max_digits=5),
        ),
    ]
