# Generated by Django 5.2.3 on 2026-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_globalsettings_receipt_ending_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Cancel Reason',
                'verbose_name_plural': 'Order Cancel Reasons',
                'ordering': ['label'],
            },
        ),
    ]
