# Generated by Django 5.2.3 on 2026-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='shift_number',
            field=models.PositiveIntegerField(default=0, help_text='Auto-incrementing shift number per branch'),
        ),
    ]
