# Generated by Django 5.2.11 on 2026-02-20 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('beverages', 'Beverages'), ('dry_goods', 'Dry Goods'), ('packaging', 'Packaging'), ('fresh_produce', 'Fresh Produce'), ('cleaning', 'Cleaning & Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('expiry_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_item_name', models.CharField(max_length=150)),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('preparation_time', models.IntegerField(default=5, help_text='In minutes')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('is_depleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('manual_adjustment', 'Manual Adjustment'), ('waste', 'Waste'), ('physical_count', 'Physical Count'), ('transfer', 'Transfer')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spillage', 'Spillage'), ('damaged', 'Damaged'), ('wrong_preparation', 'Wrong Preparation'), ('other', 'Other')], max_length=50)),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_completed', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_started', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discrepancy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discrepancy_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('physical_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.physicalcount')),
            ],
        ),
    ]
