# Generated by Django 5.2.3 on 2026-02-21 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_remove_recipe_menu_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('hidden', 'Hidden')], default='available', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='available_time_end',
            field=models.TimeField(blank=True, help_text='e.g. 11:30 for breakfast menu', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_time_start',
            field=models.TimeField(blank=True, help_text='e.g. 06:00 for breakfast menu', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated or fixed cost for profit margins', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(default=5, help_text='Average preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_takeaway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base/Dine-in Price', max_digits=10),
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Added to combo base price if selected', max_digits=10)),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_combos', to='inventory.product')),
                ('parent_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.menucategory')),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_takeaway', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='inventory.product')),
            ],
        ),
    ]
