# Generated by Django 5.2.3 on 2026-02-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='inventory.productvariation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'variation')},
        ),
    ]
