# Generated by Django 5.2.3 on 2026-02-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_recipe_variation_alter_recipe_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_raw_material',
            field=models.ForeignKey(blank=True, help_text='If set, selling this product deducts 1 unit of this raw material directly instead of using a Recipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterial'),
        ),
    ]
