# Generated by Django 5.2.11 on 2026-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_linked_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='show_in_pos',
            field=models.BooleanField(default=True, help_text='Show this category and its products in the POS interface'),
        ),
    ]
