# Generated by Django 5.2.11 on 2026-02-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_menucategory_show_in_pos'),
        ('pos', '0005_orderitem_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipe',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='pos.modifier'),
        ),
    ]
