# Generated by Django 5.2.11 on 2026-02-24 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_recipe_unique_together_recipe_modifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='item_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('subrecipe', 'Sub-Recipe')], default='raw', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='raw_material',
            field=models.ForeignKey(blank=True, help_text='Used when this recipe makes a Sub-Recipe batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy'), ('beverages', 'Beverages'), ('dry_goods', 'Dry Goods'), ('packaging', 'Packaging'), ('fresh_produce', 'Fresh Produce'), ('cleaning', 'Cleaning & Maintenance'), ('sub_recipe', 'Sub-Recipe / Prepared Item'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='BatchProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yield_quantity', models.DecimalField(decimal_places=3, help_text='Amount of sub-recipe produced', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of consumed ingredients cost', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipe_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.recipe')),
                ('subrecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_produced', to='inventory.rawmaterial')),
            ],
        ),
    ]
