import React, { useState, useEffect } from 'react';
import { toast } from 'react-hot-toast';
import { FiClock, FiLock, FiAlertTriangle, FiDollarSign, FiFileText, FiPlay } from 'react-icons/fi';
import { financeApi } from '../../api/financeApi';
import useAuthStore from '../../store/authStore';
import DataTable from '../../components/DataTable';
import PageHeader from '../../components/PageHeader';
import ConfirmModal from '../../components/ConfirmModal';

export default function EndOfDay() {
    const { user } = useAuthStore();
    const canLock = ['super_admin', 'manager'].includes(user?.role);

    const [reports, setReports] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    const [isGenerateOpen, setIsGenerateOpen] = useState(false);
    const [generateDate, setGenerateDate] = useState(new Date().toISOString().split('T')[0]);
    const [isSubmitting, setIsSubmitting] = useState(false);

    const [lockReportId, setLockReportId] = useState(null);

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {
        setIsLoading(true);
        try {
            const res = await financeApi.getEODReports();
            setReports(res.data);
        } catch (error) {
            toast.error("Failed to fetch EOD reports");
        } finally {
            setIsLoading(false);
        }
    };

    const handleGenerate = async (e) => {
        e.preventDefault();
        setIsSubmitting(true);
        const tid = toast.loading("Generating EOD Summary...");
        try {
            const res = await financeApi.generateEODReport({ date: generateDate, branch: user?.branch || 1 });
            toast.success("EOD Report Generated", { id: tid });
            setIsGenerateOpen(false);
            setReports(prev => [res.data, ...prev.filter(r => r.id !== res.data.id)]);
        } catch (error) {
            console.error("Full EOD Generation Error:", error);
            const errMsg = error.response?.data?.error || error.response?.data?.detail || error.message || "Failed to generate EOD";
            toast.error(`Error: ${errMsg}`, { id: tid });
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleLock = async () => {
        const tid = toast.loading("Locking day...");
        try {
            await financeApi.approveEODReport(lockReportId);
            toast.success("Day Locked Successfully", { id: tid });
            setLockReportId(null);
            fetchReports();
        } catch (error) {
            console.error("Full EOD Lock Error:", error);
            const errMsg = error.response?.data?.error || error.response?.data?.detail || error.message || "Failed to lock";
            toast.error(`Error: ${errMsg}`, { id: tid });
        }
    };

    const formatMoney = (val) => `${parseFloat(val || 0).toFixed(2)}`;

    const columns = [
        { header: 'Date', accessorKey: 'date' },
        { 
            header: 'Status', 
            accessorKey: 'is_locked',
            cell: info => info.getValue() 
                ? <span className="px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wider bg-green-500/20 text-green-400 flex items-center gap-1 w-max"><FiLock/> Locked</span>
                : <span className="px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wider bg-orange-500/20 text-orange-400 w-max">Draft</span>
        },
        { header: 'Gross Sales', accessorKey: 'total_sales', cell: info => <span className="font-mono">{formatMoney(info.getValue())}</span> },
        { header: 'Net Cash', accessorKey: 'net_cash', cell: info => <span className="font-mono">{formatMoney(info.getValue())}</span> },
        { 
            header: 'Discrepancy', 
            accessorKey: 'total_discrepancy', 
            cell: info => {
                const val = parseFloat(info.getValue());
                return val !== 0 
                    ? <span className="font-mono font-bold text-red-400 flex items-center gap-1"><FiAlertTriangle size={12}/> {val.toFixed(2)}</span>
                    : <span className="font-mono text-green-400">0.00</span>;
            }
        },
        { header: 'Generated At', accessorFn: row => new Date(row.created_at).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' }) },
        { header: 'Generated By', accessorFn: row => row.generated_by_name || '-' },
        {
            id: 'actions',
            header: '',
            cell: info => {
                const row = info.row.original;
                return (
                    <div className="flex gap-2 justify-end">
                        <button onClick={() => {
                            // Print/View details logic (placeholder)
                            const w = window.open("", "_blank");
                            w.document.write(`<html><body style="font-family:monospace; padding: 20px;">
                                <h2>EOD Report - ${row.date}</h2>
                                <p>Status: ${row.is_locked ? 'LOCKED' : 'DRAFT'}</p>
                                <hr/>
                                <p>Total Sales: ${row.total_sales}</p>
                                <p>Total Refunds: ${row.total_refunds}</p>
                                <p>Total Cash Items: ${row.total_cash}</p>
                                <p>Total Card Items: ${row.total_card}</p>
                                <p>Net Cash (In System): ${row.net_cash}</p>
                                <hr/>
                                <p>Reported Discrepancy: ${row.total_discrepancy}</p>
                            </body></html>`);
                        }} className="text-blue-400 hover:text-blue-300 p-1" title="View Details">
                            <FiFileText />
                        </button>
                        
                        {!row.is_locked && canLock && (
                            <button onClick={() => setLockReportId(row.id)} className="text-orange-400 hover:text-orange-300 p-1" title="Lock Day">
                                <FiLock />
                            </button>
                        )}
                    </div>
                );
            }
        }
    ];

    return (
        <div className="p-6 space-y-6 animate-fade-in">
            <PageHeader 
                title="End of Day (EOD) Operations" 
                subtitle="Review daily summaries, verify discrepancies, and lock the financial day."
                icon={FiClock}
                action={{
                    label: 'Generate New EOD',
                    icon: FiPlay,
                    onClick: () => setIsGenerateOpen(true)
                }}
            />

            <DataTable 
                columns={columns} 
                data={reports} 
                isLoading={isLoading} 
                hideSearch={true}
            />

            {/* GENERATE MODAL */}
            {isGenerateOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <form onSubmit={handleGenerate} className="bg-[#1e293b] rounded-2xl w-full max-w-sm border border-white/10 overflow-hidden shadow-2xl">
                        <div className="p-5 border-b border-white/10 flex justify-between items-center bg-[#0f172a]">
                            <h3 className="font-bold text-white text-lg">Generate EOD Summary</h3>
                            <button type="button" onClick={() => setIsGenerateOpen(false)} className="text-textMuted hover:text-white">✕</button>
                        </div>
                        <div className="p-6 space-y-4">
                            <p className="text-sm text-textMuted">This will aggregate all shifts, sales, and movements for the selected date into a single reviewable report.</p>
                            <div>
                                <label className="block text-sm font-medium text-textMuted mb-1">Target Date</label>
                                <input required type="date" className="input w-full" value={generateDate} onChange={e => setGenerateDate(e.target.value)} />
                            </div>
                        </div>
                        <div className="p-5 border-t border-white/10 bg-[#0f172a] flex justify-end gap-3">
                            <button type="button" onClick={() => setIsGenerateOpen(false)} className="px-4 py-2 rounded-lg text-textMuted hover:bg-white/5 transition-colors">Cancel</button>
                            <button type="submit" disabled={isSubmitting} className="px-5 py-2 rounded-lg bg-primary hover:bg-primary/90 text-white font-bold transition-colors shadow-lg shadow-primary/20">Generate</button>
                        </div>
                    </form>
                </div>
            )}

            {/* LOCK CONFIRMATION MODAL */}
            <ConfirmModal 
                isOpen={!!lockReportId}
                onClose={() => setLockReportId(null)}
                onConfirm={handleLock}
                title="Lock Trading Day?"
                message="Are you sure you want to lock this day? Once locked, no further sales, refunds, or expenses can be recorded for this date. This action cannot be undone."
                confirmText="Yes, Lock Day"
                confirmColor="bg-red-500 hover:bg-red-600"
            />
        </div>
    );
}
